/**
 * Seed ingredient aliases.
 *
 * This list is the source of truth for ingredient normalization across:
 *   - the pantry (every PantryItem stores `normalizedName`)
 *   - recipe ingredient lists (every RecipeIngredient stores `normalizedName`)
 *   - the matching engine (which compares normalized names on both sides)
 *
 * Editing this file is safe; running `npm run db:seed:aliases` upserts every
 * row into the `ingredient_aliases` table for any code that wants to query
 * normalization from the DB instead of the in-memory map.
 *
 * Keep `normalized` short, lowercase, singular, and free of qualifiers.
 */
export type IngredientAlias = { alias: string; normalized: string };

export const INGREDIENT_ALIASES: IngredientAlias[] = [
  // ---------- Tomato / onion / garlic / ginger ----------
  { alias: "tomato", normalized: "tomato" },
  { alias: "tomatoes", normalized: "tomato" },
  { alias: "tamatar", normalized: "tomato" },
  { alias: "roma tomato", normalized: "tomato" },
  { alias: "cherry tomato", normalized: "cherry tomato" },
  { alias: "onion", normalized: "onion" },
  { alias: "onions", normalized: "onion" },
  { alias: "pyaz", normalized: "onion" },
  { alias: "red onion", normalized: "red onion" },
  { alias: "yellow onion", normalized: "onion" },
  { alias: "white onion", normalized: "onion" },
  { alias: "scallion", normalized: "green onion" },
  { alias: "scallions", normalized: "green onion" },
  { alias: "spring onion", normalized: "green onion" },
  { alias: "green onion", normalized: "green onion" },
  { alias: "garlic", normalized: "garlic" },
  { alias: "lehsan", normalized: "garlic" },
  { alias: "lehsun", normalized: "garlic" },
  { alias: "ginger", normalized: "ginger" },
  { alias: "adrak", normalized: "ginger" },
  { alias: "ginger garlic paste", normalized: "ginger garlic paste" },
  { alias: "adrak lehsan paste", normalized: "ginger garlic paste" },

  // ---------- Chilies / peppers ----------
  { alias: "green chili", normalized: "green chili" },
  { alias: "green chilli", normalized: "green chili" },
  { alias: "green chillies", normalized: "green chili" },
  { alias: "hari mirch", normalized: "green chili" },
  { alias: "red chili", normalized: "red chili" },
  { alias: "red chilli", normalized: "red chili" },
  { alias: "lal mirch", normalized: "red chili" },
  { alias: "red chili powder", normalized: "red chili powder" },
  { alias: "lal mirch powder", normalized: "red chili powder" },
  { alias: "kashmiri chili", normalized: "kashmiri chili" },
  { alias: "kashmiri mirch", normalized: "kashmiri chili" },
  { alias: "bell pepper", normalized: "bell pepper" },
  { alias: "shimla mirch", normalized: "bell pepper" },
  { alias: "capsicum", normalized: "bell pepper" },
  { alias: "black pepper", normalized: "black pepper" },
  { alias: "kali mirch", normalized: "black pepper" },

  // ---------- Spices ----------
  { alias: "cumin", normalized: "cumin" },
  { alias: "cumin seeds", normalized: "cumin" },
  { alias: "zeera", normalized: "cumin" },
  { alias: "jeera", normalized: "cumin" },
  { alias: "coriander", normalized: "coriander" },
  { alias: "coriander seeds", normalized: "coriander" },
  { alias: "dhaniya", normalized: "coriander" },
  { alias: "cilantro", normalized: "cilantro" },
  { alias: "fresh coriander", normalized: "cilantro" },
  { alias: "hara dhaniya", normalized: "cilantro" },
  { alias: "turmeric", normalized: "turmeric" },
  { alias: "haldi", normalized: "turmeric" },
  { alias: "garam masala", normalized: "garam masala" },
  { alias: "cardamom", normalized: "cardamom" },
  { alias: "elaichi", normalized: "cardamom" },
  { alias: "green cardamom", normalized: "cardamom" },
  { alias: "black cardamom", normalized: "black cardamom" },
  { alias: "badi elaichi", normalized: "black cardamom" },
  { alias: "cinnamon", normalized: "cinnamon" },
  { alias: "darchini", normalized: "cinnamon" },
  { alias: "cloves", normalized: "cloves" },
  { alias: "laung", normalized: "cloves" },
  { alias: "bay leaf", normalized: "bay leaf" },
  { alias: "tej patta", normalized: "bay leaf" },
  { alias: "fenugreek", normalized: "fenugreek" },
  { alias: "methi", normalized: "fenugreek" },
  { alias: "kasuri methi", normalized: "kasuri methi" },
  { alias: "mustard seed", normalized: "mustard seed" },
  { alias: "rai", normalized: "mustard seed" },
  { alias: "nigella", normalized: "nigella" },
  { alias: "kalonji", normalized: "nigella" },
  { alias: "saffron", normalized: "saffron" },
  { alias: "zafran", normalized: "saffron" },

  // ---------- Mint / herbs ----------
  { alias: "mint", normalized: "mint" },
  { alias: "podina", normalized: "mint" },
  { alias: "basil", normalized: "basil" },
  { alias: "fresh basil", normalized: "basil" },
  { alias: "thai basil", normalized: "thai basil" },
  { alias: "parsley", normalized: "parsley" },
  { alias: "oregano", normalized: "oregano" },
  { alias: "thyme", normalized: "thyme" },
  { alias: "rosemary", normalized: "rosemary" },
  { alias: "dill", normalized: "dill" },

  // ---------- Proteins ----------
  { alias: "chicken", normalized: "chicken" },
  { alias: "chicken breast", normalized: "chicken breast" },
  { alias: "chicken thigh", normalized: "chicken thigh" },
  { alias: "boneless chicken", normalized: "chicken" },
  { alias: "murgh", normalized: "chicken" },
  { alias: "beef", normalized: "beef" },
  { alias: "ground beef", normalized: "ground beef" },
  { alias: "beef mince", normalized: "ground beef" },
  { alias: "qeema", normalized: "ground beef" },
  { alias: "keema", normalized: "ground beef" },
  { alias: "mutton", normalized: "mutton" },
  { alias: "lamb", normalized: "lamb" },
  { alias: "gosht", normalized: "mutton" },
  { alias: "fish", normalized: "fish" },
  { alias: "salmon", normalized: "salmon" },
  { alias: "tuna", normalized: "tuna" },
  { alias: "shrimp", normalized: "shrimp" },
  { alias: "prawn", normalized: "shrimp" },
  { alias: "prawns", normalized: "shrimp" },
  { alias: "egg", normalized: "egg" },
  { alias: "eggs", normalized: "egg" },
  { alias: "anda", normalized: "egg" },
  { alias: "tofu", normalized: "tofu" },

  // ---------- Dairy ----------
  { alias: "milk", normalized: "milk" },
  { alias: "doodh", normalized: "milk" },
  { alias: "yogurt", normalized: "yogurt" },
  { alias: "yoghurt", normalized: "yogurt" },
  { alias: "dahi", normalized: "yogurt" },
  { alias: "curd", normalized: "yogurt" },
  { alias: "greek yogurt", normalized: "greek yogurt" },
  { alias: "cream", normalized: "cream" },
  { alias: "heavy cream", normalized: "cream" },
  { alias: "double cream", normalized: "cream" },
  { alias: "malai", normalized: "cream" },
  { alias: "butter", normalized: "butter" },
  { alias: "makhan", normalized: "butter" },
  { alias: "ghee", normalized: "ghee" },
  { alias: "clarified butter", normalized: "ghee" },
  { alias: "mozzarella", normalized: "mozzarella" },
  { alias: "mozzarella cheese", normalized: "mozzarella" },
  { alias: "parmesan", normalized: "parmesan" },
  { alias: "parmesan cheese", normalized: "parmesan" },
  { alias: "parmigiano", normalized: "parmesan" },
  { alias: "cheddar", normalized: "cheddar" },
  { alias: "cheddar cheese", normalized: "cheddar" },
  { alias: "feta", normalized: "feta" },
  { alias: "ricotta", normalized: "ricotta" },
  { alias: "paneer", normalized: "paneer" },

  // ---------- Grains / starches ----------
  { alias: "rice", normalized: "rice" },
  { alias: "basmati", normalized: "basmati rice" },
  { alias: "basmati rice", normalized: "basmati rice" },
  { alias: "jasmine rice", normalized: "jasmine rice" },
  { alias: "white rice", normalized: "rice" },
  { alias: "brown rice", normalized: "brown rice" },
  { alias: "chawal", normalized: "rice" },
  { alias: "all purpose flour", normalized: "all purpose flour" },
  { alias: "all-purpose flour", normalized: "all purpose flour" },
  { alias: "plain flour", normalized: "all purpose flour" },
  { alias: "maida", normalized: "all purpose flour" },
  { alias: "wheat flour", normalized: "wheat flour" },
  { alias: "atta", normalized: "wheat flour" },
  { alias: "chickpea flour", normalized: "chickpea flour" },
  { alias: "besan", normalized: "chickpea flour" },
  { alias: "gram flour", normalized: "chickpea flour" },
  { alias: "cornstarch", normalized: "cornstarch" },
  { alias: "corn flour", normalized: "cornstarch" },
  { alias: "pasta", normalized: "pasta" },
  { alias: "spaghetti", normalized: "spaghetti" },
  { alias: "penne", normalized: "penne" },
  { alias: "fettuccine", normalized: "fettuccine" },
  { alias: "noodles", normalized: "noodles" },
  { alias: "ramen noodles", normalized: "ramen noodles" },
  { alias: "udon", normalized: "udon" },
  { alias: "soba", normalized: "soba" },
  { alias: "bread", normalized: "bread" },
  { alias: "bread crumbs", normalized: "bread crumbs" },
  { alias: "breadcrumbs", normalized: "bread crumbs" },
  { alias: "panko", normalized: "panko" },

  // ---------- Vegetables ----------
  { alias: "potato", normalized: "potato" },
  { alias: "potatoes", normalized: "potato" },
  { alias: "aloo", normalized: "potato" },
  { alias: "carrot", normalized: "carrot" },
  { alias: "gajar", normalized: "carrot" },
  { alias: "peas", normalized: "peas" },
  { alias: "matar", normalized: "peas" },
  { alias: "spinach", normalized: "spinach" },
  { alias: "palak", normalized: "spinach" },
  { alias: "cauliflower", normalized: "cauliflower" },
  { alias: "gobi", normalized: "cauliflower" },
  { alias: "cabbage", normalized: "cabbage" },
  { alias: "patta gobi", normalized: "cabbage" },
  { alias: "okra", normalized: "okra" },
  { alias: "bhindi", normalized: "okra" },
  { alias: "eggplant", normalized: "eggplant" },
  { alias: "aubergine", normalized: "eggplant" },
  { alias: "baingan", normalized: "eggplant" },
  { alias: "zucchini", normalized: "zucchini" },
  { alias: "courgette", normalized: "zucchini" },
  { alias: "mushroom", normalized: "mushroom" },
  { alias: "mushrooms", normalized: "mushroom" },
  { alias: "lemon", normalized: "lemon" },
  { alias: "lime", normalized: "lime" },
  { alias: "nimbu", normalized: "lemon" },
  { alias: "cucumber", normalized: "cucumber" },
  { alias: "kheera", normalized: "cucumber" },
  { alias: "lettuce", normalized: "lettuce" },
  { alias: "broccoli", normalized: "broccoli" },
  { alias: "corn", normalized: "corn" },
  { alias: "sweet corn", normalized: "corn" },
  { alias: "bok choy", normalized: "bok choy" },
  { alias: "pak choi", normalized: "bok choy" },

  // ---------- Asian sauces / pantry ----------
  { alias: "soy sauce", normalized: "soy sauce" },
  { alias: "light soy sauce", normalized: "soy sauce" },
  { alias: "dark soy sauce", normalized: "dark soy sauce" },
  { alias: "tamari", normalized: "soy sauce" },
  { alias: "shoyu", normalized: "soy sauce" },
  { alias: "fish sauce", normalized: "fish sauce" },
  { alias: "oyster sauce", normalized: "oyster sauce" },
  { alias: "hoisin sauce", normalized: "hoisin sauce" },
  { alias: "sesame oil", normalized: "sesame oil" },
  { alias: "rice vinegar", normalized: "rice vinegar" },
  { alias: "mirin", normalized: "mirin" },
  { alias: "sake", normalized: "sake" },
  { alias: "miso", normalized: "miso" },
  { alias: "miso paste", normalized: "miso" },
  { alias: "sriracha", normalized: "sriracha" },
  { alias: "schezwan sauce", normalized: "schezwan sauce" },
  { alias: "chili oil", normalized: "chili oil" },
  { alias: "rice wine", normalized: "rice wine" },
  { alias: "nori", normalized: "nori" },
  { alias: "dashi", normalized: "dashi" },

  // ---------- Western pantry / sauces ----------
  { alias: "olive oil", normalized: "olive oil" },
  { alias: "extra virgin olive oil", normalized: "olive oil" },
  { alias: "vegetable oil", normalized: "vegetable oil" },
  { alias: "canola oil", normalized: "vegetable oil" },
  { alias: "sunflower oil", normalized: "vegetable oil" },
  { alias: "salt", normalized: "salt" },
  { alias: "namak", normalized: "salt" },
  { alias: "sugar", normalized: "sugar" },
  { alias: "cheeni", normalized: "sugar" },
  { alias: "honey", normalized: "honey" },
  { alias: "maple syrup", normalized: "maple syrup" },
  { alias: "vinegar", normalized: "vinegar" },
  { alias: "white vinegar", normalized: "vinegar" },
  { alias: "balsamic vinegar", normalized: "balsamic vinegar" },
  { alias: "ketchup", normalized: "ketchup" },
  { alias: "tomato ketchup", normalized: "ketchup" },
  { alias: "mayonnaise", normalized: "mayonnaise" },
  { alias: "mayo", normalized: "mayonnaise" },
  { alias: "mustard", normalized: "mustard" },
  { alias: "dijon mustard", normalized: "dijon mustard" },
  { alias: "tomato paste", normalized: "tomato paste" },
  { alias: "tomato puree", normalized: "tomato puree" },
  { alias: "tomato sauce", normalized: "tomato sauce" },
  { alias: "passata", normalized: "tomato sauce" },
  { alias: "pesto", normalized: "pesto" },

  // ---------- Legumes ----------
  { alias: "chickpeas", normalized: "chickpeas" },
  { alias: "chana", normalized: "chickpeas" },
  { alias: "garbanzo beans", normalized: "chickpeas" },
  { alias: "kidney beans", normalized: "kidney beans" },
  { alias: "rajma", normalized: "kidney beans" },
  { alias: "lentils", normalized: "lentils" },
  { alias: "daal", normalized: "lentils" },
  { alias: "dal", normalized: "lentils" },
  { alias: "red lentils", normalized: "red lentils" },
  { alias: "masoor dal", normalized: "red lentils" },
  { alias: "yellow lentils", normalized: "yellow lentils" },
  { alias: "moong dal", normalized: "yellow lentils" },
  { alias: "black beans", normalized: "black beans" },

  // ---------- Nuts / seeds ----------
  { alias: "almond", normalized: "almond" },
  { alias: "almonds", normalized: "almond" },
  { alias: "badam", normalized: "almond" },
  { alias: "cashew", normalized: "cashew" },
  { alias: "cashews", normalized: "cashew" },
  { alias: "kaju", normalized: "cashew" },
  { alias: "peanut", normalized: "peanut" },
  { alias: "peanuts", normalized: "peanut" },
  { alias: "sesame seeds", normalized: "sesame seeds" },
  { alias: "til", normalized: "sesame seeds" },
];
