import { PrismaClient, type Cuisine, type Difficulty, type SpiceLevel, type MealType } from "@prisma/client";

const prisma = new PrismaClient();

type SeedIngredient = {
  display: string;
  normalized: string;
  required: boolean;
  notes?: string;
};

type SeedRecipe = {
  slug: string;
  title: string;
  description: string;
  cuisine: Cuisine;
  prepTime: number;
  cookTime: number;
  difficulty: Difficulty;
  spiceLevel: SpiceLevel;
  mealType: MealType[];
  servings: number;
  vegetarian: boolean;
  tags: string[];
  ingredients: SeedIngredient[];
};

const RECIPES: SeedRecipe[] = [
  // ─────────── Pakistani (8) ───────────
  {
    slug: "daal",
    title: "Yellow Daal",
    description: "Comforting lentils tempered with cumin and garlic.",
    cuisine: "pakistani",
    prepTime: 5,
    cookTime: 25,
    difficulty: "easy",
    spiceLevel: "mild",
    mealType: ["lunch", "dinner"],
    servings: 4,
    vegetarian: true,
    tags: ["one-pot", "weeknight"],
    ingredients: [
      { display: "yellow lentils", normalized: "yellow lentils", required: true },
      { display: "onion", normalized: "onion", required: true },
      { display: "tomato", normalized: "tomato", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "ginger", normalized: "ginger", required: false },
      { display: "cumin", normalized: "cumin", required: false },
      { display: "turmeric", normalized: "turmeric", required: false },
    ],
  },
  {
    slug: "chicken-karahi",
    title: "Chicken Karahi",
    description: "Bold tomato-based chicken cooked fast over high heat.",
    cuisine: "pakistani",
    prepTime: 10,
    cookTime: 30,
    difficulty: "medium",
    spiceLevel: "hot",
    mealType: ["dinner"],
    servings: 4,
    vegetarian: false,
    tags: ["weeknight", "showstopper"],
    ingredients: [
      { display: "chicken", normalized: "chicken", required: true },
      { display: "tomato", normalized: "tomato", required: true },
      { display: "ginger", normalized: "ginger", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "green chili", normalized: "green chili", required: true },
      { display: "garam masala", normalized: "garam masala", required: false },
      { display: "cumin", normalized: "cumin", required: false },
    ],
  },
  {
    slug: "aloo-gosht",
    title: "Aloo Gosht",
    description: "Beef and potato curry — slow-simmered, deeply spiced.",
    cuisine: "pakistani",
    prepTime: 10,
    cookTime: 60,
    difficulty: "medium",
    spiceLevel: "medium",
    mealType: ["dinner"],
    servings: 4,
    vegetarian: false,
    tags: ["slow"],
    ingredients: [
      { display: "beef", normalized: "beef", required: true },
      { display: "potato", normalized: "potato", required: true },
      { display: "onion", normalized: "onion", required: true },
      { display: "tomato", normalized: "tomato", required: true },
      { display: "ginger", normalized: "ginger", required: false },
      { display: "garlic", normalized: "garlic", required: false },
      { display: "garam masala", normalized: "garam masala", required: false },
    ],
  },
  {
    slug: "chana-masala",
    title: "Chana Masala",
    description: "Chickpeas in a fragrant tomato-onion gravy.",
    cuisine: "pakistani",
    prepTime: 5,
    cookTime: 25,
    difficulty: "easy",
    spiceLevel: "medium",
    mealType: ["lunch", "dinner"],
    servings: 4,
    vegetarian: true,
    tags: ["pantry-friendly"],
    ingredients: [
      { display: "chickpeas", normalized: "chickpeas", required: true },
      { display: "onion", normalized: "onion", required: true },
      { display: "tomato", normalized: "tomato", required: true },
      { display: "ginger", normalized: "ginger", required: false },
      { display: "garlic", normalized: "garlic", required: false },
      { display: "cumin", normalized: "cumin", required: false },
      { display: "garam masala", normalized: "garam masala", required: false },
    ],
  },
  {
    slug: "egg-bhurji",
    title: "Egg Bhurji",
    description: "Spiced scrambled eggs with onions, tomatoes, and chili.",
    cuisine: "pakistani",
    prepTime: 5,
    cookTime: 10,
    difficulty: "easy",
    spiceLevel: "medium",
    mealType: ["breakfast", "lunch"],
    servings: 2,
    vegetarian: true,
    tags: ["breakfast", "fast"],
    ingredients: [
      { display: "egg", normalized: "egg", required: true },
      { display: "onion", normalized: "onion", required: true },
      { display: "tomato", normalized: "tomato", required: true },
      { display: "green chili", normalized: "green chili", required: false },
      { display: "turmeric", normalized: "turmeric", required: false },
    ],
  },
  {
    slug: "qeema-aloo",
    title: "Keema Aloo",
    description: "Ground beef with potatoes — quick, weeknight-friendly.",
    cuisine: "pakistani",
    prepTime: 10,
    cookTime: 30,
    difficulty: "easy",
    spiceLevel: "medium",
    mealType: ["dinner"],
    servings: 4,
    vegetarian: false,
    tags: ["weeknight"],
    ingredients: [
      { display: "ground beef", normalized: "ground beef", required: true },
      { display: "potato", normalized: "potato", required: true },
      { display: "onion", normalized: "onion", required: true },
      { display: "tomato", normalized: "tomato", required: true },
      { display: "ginger", normalized: "ginger", required: false },
      { display: "garlic", normalized: "garlic", required: false },
      { display: "garam masala", normalized: "garam masala", required: false },
    ],
  },
  {
    slug: "aloo-paratha",
    title: "Aloo Paratha",
    description: "Flatbread stuffed with spiced mashed potato.",
    cuisine: "pakistani",
    prepTime: 20,
    cookTime: 20,
    difficulty: "medium",
    spiceLevel: "mild",
    mealType: ["breakfast"],
    servings: 4,
    vegetarian: true,
    tags: ["breakfast"],
    ingredients: [
      { display: "wheat flour", normalized: "wheat flour", required: true },
      { display: "potato", normalized: "potato", required: true },
      { display: "onion", normalized: "onion", required: false },
      { display: "green chili", normalized: "green chili", required: false },
      { display: "cumin", normalized: "cumin", required: false },
    ],
  },
  {
    slug: "palak-paneer",
    title: "Palak Paneer",
    description: "Creamy spinach with cubes of fresh paneer.",
    cuisine: "pakistani",
    prepTime: 10,
    cookTime: 25,
    difficulty: "medium",
    spiceLevel: "mild",
    mealType: ["dinner"],
    servings: 4,
    vegetarian: true,
    tags: ["vegetarian"],
    ingredients: [
      { display: "spinach", normalized: "spinach", required: true },
      { display: "paneer", normalized: "paneer", required: true },
      { display: "onion", normalized: "onion", required: true },
      { display: "garlic", normalized: "garlic", required: false },
      { display: "ginger", normalized: "ginger", required: false },
      { display: "cumin", normalized: "cumin", required: false },
      { display: "garam masala", normalized: "garam masala", required: false },
    ],
  },

  // ─────────── Indo-Chinese (4) ───────────
  {
    slug: "chicken-manchurian",
    title: "Chicken Manchurian",
    description: "Crispy chicken in a tangy soy-garlic sauce.",
    cuisine: "indo_chinese",
    prepTime: 15,
    cookTime: 20,
    difficulty: "medium",
    spiceLevel: "medium",
    mealType: ["dinner"],
    servings: 4,
    vegetarian: false,
    tags: ["takeout-style"],
    ingredients: [
      { display: "chicken", normalized: "chicken", required: true },
      { display: "soy sauce", normalized: "soy sauce", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "ginger", normalized: "ginger", required: true },
      { display: "green onion", normalized: "green onion", required: false },
      { display: "cornstarch", normalized: "cornstarch", required: false },
    ],
  },
  {
    slug: "veg-hakka-noodles",
    title: "Veg Hakka Noodles",
    description: "Stir-fried noodles tossed with crisp vegetables and soy.",
    cuisine: "indo_chinese",
    prepTime: 10,
    cookTime: 15,
    difficulty: "easy",
    spiceLevel: "mild",
    mealType: ["lunch", "dinner"],
    servings: 3,
    vegetarian: true,
    tags: ["one-pan", "fast"],
    ingredients: [
      { display: "noodles", normalized: "noodles", required: true },
      { display: "cabbage", normalized: "cabbage", required: true },
      { display: "carrot", normalized: "carrot", required: true },
      { display: "soy sauce", normalized: "soy sauce", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "green onion", normalized: "green onion", required: false },
    ],
  },
  {
    slug: "chilli-paneer",
    title: "Chilli Paneer",
    description: "Crispy paneer in a sweet-spicy soy sauce stir-fry.",
    cuisine: "indo_chinese",
    prepTime: 10,
    cookTime: 15,
    difficulty: "easy",
    spiceLevel: "hot",
    mealType: ["dinner", "snack"],
    servings: 3,
    vegetarian: true,
    tags: ["vegetarian", "starter"],
    ingredients: [
      { display: "paneer", normalized: "paneer", required: true },
      { display: "bell pepper", normalized: "bell pepper", required: true },
      { display: "soy sauce", normalized: "soy sauce", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "green chili", normalized: "green chili", required: false },
      { display: "cornstarch", normalized: "cornstarch", required: false },
    ],
  },
  {
    slug: "schezwan-fried-rice",
    title: "Schezwan Fried Rice",
    description: "Fiery wok-tossed rice with a kick of garlic-chili sauce.",
    cuisine: "indo_chinese",
    prepTime: 5,
    cookTime: 15,
    difficulty: "easy",
    spiceLevel: "hot",
    mealType: ["lunch", "dinner"],
    servings: 3,
    vegetarian: true,
    tags: ["leftover-rice"],
    ingredients: [
      { display: "rice", normalized: "rice", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "soy sauce", normalized: "soy sauce", required: true },
      { display: "schezwan sauce", normalized: "schezwan sauce", required: false },
      { display: "carrot", normalized: "carrot", required: false },
      { display: "green onion", normalized: "green onion", required: false },
    ],
  },

  // ─────────── Chinese (3) ───────────
  {
    slug: "egg-fried-rice",
    title: "Egg Fried Rice",
    description: "The classic — day-old rice, eggs, soy, ready in 10.",
    cuisine: "chinese",
    prepTime: 5,
    cookTime: 10,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["lunch", "dinner"],
    servings: 2,
    vegetarian: true,
    tags: ["leftover-rice", "fast"],
    ingredients: [
      { display: "rice", normalized: "rice", required: true },
      { display: "egg", normalized: "egg", required: true },
      { display: "soy sauce", normalized: "soy sauce", required: true },
      { display: "green onion", normalized: "green onion", required: false },
      { display: "garlic", normalized: "garlic", required: false },
    ],
  },
  {
    slug: "kung-pao-chicken",
    title: "Kung Pao Chicken",
    description: "Sichuan stir-fry with peanuts and dried chilies.",
    cuisine: "chinese",
    prepTime: 15,
    cookTime: 15,
    difficulty: "medium",
    spiceLevel: "hot",
    mealType: ["dinner"],
    servings: 3,
    vegetarian: false,
    tags: ["takeout-style"],
    ingredients: [
      { display: "chicken", normalized: "chicken", required: true },
      { display: "peanut", normalized: "peanut", required: true },
      { display: "soy sauce", normalized: "soy sauce", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "ginger", normalized: "ginger", required: false },
      { display: "rice vinegar", normalized: "rice vinegar", required: false },
    ],
  },
  {
    slug: "tomato-egg-stir-fry",
    title: "Tomato Egg Stir-Fry",
    description: "Silky scrambled eggs folded into stewed tomatoes.",
    cuisine: "chinese",
    prepTime: 5,
    cookTime: 10,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["lunch", "dinner"],
    servings: 2,
    vegetarian: true,
    tags: ["fast", "comfort"],
    ingredients: [
      { display: "tomato", normalized: "tomato", required: true },
      { display: "egg", normalized: "egg", required: true },
      { display: "green onion", normalized: "green onion", required: false },
      { display: "soy sauce", normalized: "soy sauce", required: false },
    ],
  },

  // ─────────── Japanese (4) ───────────
  {
    slug: "tamagoyaki",
    title: "Tamagoyaki",
    description: "Sweet-savory rolled Japanese omelet.",
    cuisine: "japanese",
    prepTime: 5,
    cookTime: 10,
    difficulty: "medium",
    spiceLevel: "none",
    mealType: ["breakfast", "side"],
    servings: 2,
    vegetarian: true,
    tags: ["breakfast"],
    ingredients: [
      { display: "egg", normalized: "egg", required: true },
      { display: "soy sauce", normalized: "soy sauce", required: true },
      { display: "mirin", normalized: "mirin", required: false },
    ],
  },
  {
    slug: "oyakodon",
    title: "Oyakodon",
    description: "Chicken and egg simmered in dashi over rice.",
    cuisine: "japanese",
    prepTime: 5,
    cookTime: 15,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["lunch", "dinner"],
    servings: 2,
    vegetarian: false,
    tags: ["donburi"],
    ingredients: [
      { display: "chicken", normalized: "chicken", required: true },
      { display: "egg", normalized: "egg", required: true },
      { display: "rice", normalized: "rice", required: true },
      { display: "onion", normalized: "onion", required: true },
      { display: "soy sauce", normalized: "soy sauce", required: true },
      { display: "mirin", normalized: "mirin", required: false },
      { display: "dashi", normalized: "dashi", required: false },
    ],
  },
  {
    slug: "miso-soup",
    title: "Miso Soup",
    description: "Five-minute soup of miso, tofu, and green onion.",
    cuisine: "japanese",
    prepTime: 2,
    cookTime: 8,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["side", "lunch"],
    servings: 2,
    vegetarian: true,
    tags: ["light", "fast"],
    ingredients: [
      { display: "miso", normalized: "miso", required: true },
      { display: "tofu", normalized: "tofu", required: false },
      { display: "green onion", normalized: "green onion", required: false },
      { display: "dashi", normalized: "dashi", required: false },
    ],
  },
  {
    slug: "onigiri",
    title: "Onigiri",
    description: "Hand-shaped rice triangles wrapped in nori.",
    cuisine: "japanese",
    prepTime: 10,
    cookTime: 0,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["snack", "lunch"],
    servings: 2,
    vegetarian: true,
    tags: ["meal-prep"],
    ingredients: [
      { display: "rice", normalized: "rice", required: true },
      { display: "nori", normalized: "nori", required: true },
      { display: "tuna", normalized: "tuna", required: false, notes: "common filling" },
    ],
  },

  // ─────────── Italian (5) ───────────
  {
    slug: "spaghetti-aglio-e-olio",
    title: "Spaghetti Aglio e Olio",
    description: "Garlic, olive oil, and chili — the elegant pantry pasta.",
    cuisine: "italian",
    prepTime: 5,
    cookTime: 15,
    difficulty: "easy",
    spiceLevel: "mild",
    mealType: ["lunch", "dinner"],
    servings: 2,
    vegetarian: true,
    tags: ["pantry-friendly", "fast"],
    ingredients: [
      { display: "spaghetti", normalized: "spaghetti", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "olive oil", normalized: "olive oil", required: true },
      { display: "parsley", normalized: "parsley", required: false },
      { display: "red chili", normalized: "red chili", required: false },
    ],
  },
  {
    slug: "pasta-carbonara",
    title: "Pasta Carbonara",
    description: "Eggs, pecorino, and crispy bacon — no cream needed.",
    cuisine: "italian",
    prepTime: 5,
    cookTime: 15,
    difficulty: "medium",
    spiceLevel: "none",
    mealType: ["dinner"],
    servings: 2,
    vegetarian: false,
    tags: ["weeknight"],
    ingredients: [
      { display: "spaghetti", normalized: "spaghetti", required: true },
      { display: "egg", normalized: "egg", required: true },
      { display: "bacon", normalized: "bacon", required: true },
      { display: "parmesan", normalized: "parmesan", required: true },
      { display: "black pepper", normalized: "black pepper", required: false },
    ],
  },
  {
    slug: "marinara-pasta",
    title: "Marinara Pasta",
    description: "Tomato, garlic, basil — the simplest red sauce.",
    cuisine: "italian",
    prepTime: 5,
    cookTime: 20,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["lunch", "dinner"],
    servings: 3,
    vegetarian: true,
    tags: ["pantry-friendly"],
    ingredients: [
      { display: "pasta", normalized: "pasta", required: true },
      { display: "tomato", normalized: "tomato", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "olive oil", normalized: "olive oil", required: false },
      { display: "basil", normalized: "basil", required: false },
    ],
  },
  {
    slug: "caprese-salad",
    title: "Caprese Salad",
    description: "Tomato, mozzarella, basil, olive oil. That's it.",
    cuisine: "italian",
    prepTime: 5,
    cookTime: 0,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["side", "lunch"],
    servings: 2,
    vegetarian: true,
    tags: ["no-cook"],
    ingredients: [
      { display: "tomato", normalized: "tomato", required: true },
      { display: "mozzarella", normalized: "mozzarella", required: true },
      { display: "basil", normalized: "basil", required: true },
      { display: "olive oil", normalized: "olive oil", required: false },
    ],
  },
  {
    slug: "bruschetta",
    title: "Bruschetta",
    description: "Toasted bread piled with garlicky tomato and basil.",
    cuisine: "italian",
    prepTime: 10,
    cookTime: 5,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["snack", "side"],
    servings: 2,
    vegetarian: true,
    tags: ["starter"],
    ingredients: [
      { display: "bread", normalized: "bread", required: true },
      { display: "tomato", normalized: "tomato", required: true },
      { display: "garlic", normalized: "garlic", required: true },
      { display: "olive oil", normalized: "olive oil", required: false },
      { display: "basil", normalized: "basil", required: false },
    ],
  },

  // ─────────── Western (6) ───────────
  {
    slug: "scrambled-eggs",
    title: "Scrambled Eggs",
    description: "Slow-cooked, creamy curds. Five minutes.",
    cuisine: "western",
    prepTime: 1,
    cookTime: 5,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["breakfast"],
    servings: 1,
    vegetarian: true,
    tags: ["breakfast", "fast"],
    ingredients: [
      { display: "egg", normalized: "egg", required: true },
      { display: "butter", normalized: "butter", required: false },
      { display: "milk", normalized: "milk", required: false },
    ],
  },
  {
    slug: "cheese-omelet",
    title: "Cheese Omelet",
    description: "Folded eggs with melted cheddar.",
    cuisine: "western",
    prepTime: 2,
    cookTime: 6,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["breakfast"],
    servings: 1,
    vegetarian: true,
    tags: ["breakfast"],
    ingredients: [
      { display: "egg", normalized: "egg", required: true },
      { display: "cheddar", normalized: "cheddar", required: true },
      { display: "butter", normalized: "butter", required: false },
    ],
  },
  {
    slug: "grilled-cheese",
    title: "Grilled Cheese Sandwich",
    description: "Buttery bread, melty cheese, golden crust.",
    cuisine: "western",
    prepTime: 2,
    cookTime: 6,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["lunch", "snack"],
    servings: 1,
    vegetarian: true,
    tags: ["sandwich", "fast"],
    ingredients: [
      { display: "bread", normalized: "bread", required: true },
      { display: "cheddar", normalized: "cheddar", required: true },
      { display: "butter", normalized: "butter", required: false },
    ],
  },
  {
    slug: "pancakes",
    title: "Pancakes",
    description: "Fluffy stack with butter and maple syrup.",
    cuisine: "western",
    prepTime: 5,
    cookTime: 10,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["breakfast"],
    servings: 2,
    vegetarian: true,
    tags: ["breakfast"],
    ingredients: [
      { display: "all purpose flour", normalized: "all purpose flour", required: true },
      { display: "egg", normalized: "egg", required: true },
      { display: "milk", normalized: "milk", required: true },
      { display: "butter", normalized: "butter", required: false },
      { display: "maple syrup", normalized: "maple syrup", required: false },
    ],
  },
  {
    slug: "french-toast",
    title: "French Toast",
    description: "Egg-soaked bread, pan-fried until caramelized.",
    cuisine: "western",
    prepTime: 5,
    cookTime: 10,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["breakfast"],
    servings: 2,
    vegetarian: true,
    tags: ["breakfast"],
    ingredients: [
      { display: "bread", normalized: "bread", required: true },
      { display: "egg", normalized: "egg", required: true },
      { display: "milk", normalized: "milk", required: true },
      { display: "cinnamon", normalized: "cinnamon", required: false },
      { display: "maple syrup", normalized: "maple syrup", required: false },
    ],
  },
  {
    slug: "tuna-pasta-salad",
    title: "Tuna Pasta Salad",
    description: "Cold pasta tossed with tuna and a creamy lemon dressing.",
    cuisine: "western",
    prepTime: 10,
    cookTime: 10,
    difficulty: "easy",
    spiceLevel: "none",
    mealType: ["lunch"],
    servings: 3,
    vegetarian: false,
    tags: ["meal-prep", "no-cook-mostly"],
    ingredients: [
      { display: "pasta", normalized: "pasta", required: true },
      { display: "tuna", normalized: "tuna", required: true },
      { display: "mayonnaise", normalized: "mayonnaise", required: true },
      { display: "lemon", normalized: "lemon", required: false },
      { display: "onion", normalized: "onion", required: false },
    ],
  },
];

async function main() {
  console.log(`Seeding ${RECIPES.length} recipes…`);

  for (const recipe of RECIPES) {
    const totalTime = recipe.prepTime + recipe.cookTime;
    const upserted = await prisma.recipe.upsert({
      where: { slug: recipe.slug },
      update: {
        title: recipe.title,
        description: recipe.description,
        cuisine: recipe.cuisine,
        prepTime: recipe.prepTime,
        cookTime: recipe.cookTime,
        totalTime,
        difficulty: recipe.difficulty,
        spiceLevel: recipe.spiceLevel,
        mealType: recipe.mealType,
        servings: recipe.servings,
        vegetarian: recipe.vegetarian,
        tags: recipe.tags,
      },
      create: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        cuisine: recipe.cuisine,
        prepTime: recipe.prepTime,
        cookTime: recipe.cookTime,
        totalTime,
        difficulty: recipe.difficulty,
        spiceLevel: recipe.spiceLevel,
        mealType: recipe.mealType,
        servings: recipe.servings,
        vegetarian: recipe.vegetarian,
        tags: recipe.tags,
      },
    });

    await prisma.recipeIngredient.deleteMany({ where: { recipeId: upserted.id } });
    await prisma.recipeIngredient.createMany({
      data: recipe.ingredients.map((ing) => ({
        recipeId: upserted.id,
        ingredientName: ing.display,
        normalizedName: ing.normalized,
        required: ing.required,
        notes: ing.notes ?? null,
      })),
    });
  }

  console.log(`Done. ${RECIPES.length} recipes seeded.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
